# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
    - name: Deploy
      run: at now +1 minutes -f .github/workflows/deploy_api.sh
